In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
d = pd.read_csv("/content/city_day.csv")
print(d.shape)
d.describe()

(29531, 16)


PM2.5          PM10            NO           NO2           NOx  \
count  24933.000000  18391.000000  25949.000000  25946.000000  25346.000000   
mean      67.450578    118.127103     17.574730     28.560659     32.309123   
std       64.661449     90.605110     22.785846     24.474746     31.646011   
min        0.040000      0.010000      0.020000      0.010000      0.000000   
25%       28.820000     56.255000      5.630000     11.750000     12.820000   
50%       48.570000     95.680000      9.890000     21.690000     23.520000   
75%       80.590000    149.745000     19.950000     37.620000     40.127500   
max      949.990000   1000.000000    390.680000    362.210000    467.630000   

                NH3            CO           SO2            O3       Benzene  \
count  19203.000000  27472.000000  25677.000000  25509.000000  23908.000000   
mean      23.483476      2.248598     14.531977     34.491430      3.280840   
std       25.684275      6.962884     18.133775     21.694928     15.811136   
min        0.010000      0.000000      0.010000      0.010000      0.000000   
25%        8.580000      0.510000      5.670000     18.860000      0.120000   
50%       15.850000      0.890000      9.160000     30.840000      1.070000   
75%       30.020000      1.450000     15.220000     45.570000      3.080000   
max      352.890000    175.810000    193.860000    257.730000    455.030000   

            Toluene        Xylene           AQI  
count  21490.000000  11422.000000  24850.000000  
mean       8.700972      3.070128    166.463581  
std       19.969164      6.323247    140.696585  
min        0.000000      0.000000     13.000000  
25%        0.600000      0.140000     81.000000  
50%        2.970000      0.980000    118.000000  
75%        9.150000      3.350000    208.000000  
max      454.850000    170.370000   2049.000000

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   City        29531 non-null  object 
 1   Date        29531 non-null  object 
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object 
dtypes: float64(13), object(3)
memory usage: 3.6+ MB


In [ ]:
d.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [ ]:
pmean=d["PM2.5"].mean()
d["PM2.5"].fillna(pmean,inplace=True)
pmmean=d["PM10"].mean()
d["PM10"].fillna(pmmean,inplace=True)
pmmean=d["NO"].mean()
d["NO"].fillna(pmmean,inplace=True)
pmmean=d["NO2"].mean()
d["NO2"].fillna(pmmean,inplace=True)
pmmean=d["NOx"].mean()
d["NOx"].fillna(pmmean,inplace=True)
pmmean=d["NH3"].mean()
d["NH3"].fillna(pmmean,inplace=True)
pmmean=d["CO"].mean()
d["CO"].fillna(pmmean,inplace=True)
pmmean=d["SO2"].mean()
d["SO2"].fillna(pmmean,inplace=True)
pmmean=d["O3"].mean()
d["O3"].fillna(pmmean,inplace=True)
pmmean=d["Benzene"].mean()
d["Benzene"].fillna(pmmean,inplace=True)
pmmean=d["Toluene"].mean()
d["Toluene"].fillna(pmmean,inplace=True)
pmmean=d["Xylene"].mean()
d["Xylene"].fillna(pmmean,inplace=True)
pmmean=d["AQI"].mean()
d["AQI"].fillna(pmmean,inplace=True)


In [ ]:
d.isnull().sum()

City             0
Date             0
PM2.5            0
PM10             0
NO               0
NO2              0
NOx              0
NH3              0
CO               0
SO2              0
O3               0
Benzene          0
Toluene          0
Xylene           0
AQI              0
AQI_Bucket    4681
dtype: int64

In [ ]:
x=d.iloc[:,2:13].values
y=d.iloc[:,-2].values

In [ ]:
x

array([[6.74505779e+01, 1.18127103e+02, 9.20000000e-01, ...,
        1.33360000e+02, 0.00000000e+00, 2.00000000e-02],
       [6.74505779e+01, 1.18127103e+02, 9.70000000e-01, ...,
        3.40600000e+01, 3.68000000e+00, 5.50000000e+00],
       [6.74505779e+01, 1.18127103e+02, 1.74000000e+01, ...,
        3.07000000e+01, 6.80000000e+00, 1.64000000e+01],
       ...,
       [2.29100000e+01, 6.57300000e+01, 3.45000000e+00, ...,
        3.09600000e+01, 1.00000000e-02, 1.00000000e-02],
       [1.66400000e+01, 4.99700000e+01, 4.05000000e+00, ...,
        2.83000000e+01, 0.00000000e+00, 0.00000000e+00],
       [1.50000000e+01, 6.60000000e+01, 4.00000000e-01, ...,
        1.70500000e+01, 3.28084030e+00, 8.70097208e+00]])

In [ ]:
y


array([166.46358149, 166.46358149, 166.46358149, ...,  68.        ,
        54.        ,  50.        ])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
model= linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [ ]:
model.predict([[67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68000,5.500000]])

array([152.71532406])

In [ ]:
y_pred=model.predict(X_test)
y_pred.shape

(5907,)

In [ ]:
mse=mean_squared_error(y_test,y_pred)

In [ ]:
a=model.coef_
print(a)
b=model.intercept_
print(b)
y_pred=b+a*x
y_pred

[ 0.98061701  0.2771801  -0.0528477   0.3934255   0.1277805  -0.04938855
 10.20726186  0.61262133  0.19309406 -0.20746059  0.14279288]
15.225035033489604


array([81.36821925, 47.96751695, 15.17377277, 21.39788109, 17.32830201,
       14.06522013, 25.12607904, 30.26488857, 21.80181866, 14.46158005,
       16.01039588])

In [ ]:
print(X_test.shape)
print(y_test.shape)
print(y_pred.shape)


(5907, 11)
(5907,)
(5907,)


In [ ]:
mse=mean_squared_error(y_test,y_pred)
print(mse)
r2 = r2_score(y_test, y_pred)
print(r2)

2927.2763410398684
0.8058261217041185


In [ ]:
new_d=np.array([67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68000,5.500000])
new_p=b+np.dot(new_d,a)
print(new_p)

152.71532406482436
